version: '3.8'

services:
  # # Adminer for database management
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - "8080:8080"
    
    
  # # MySQL Service
  # mysql:
  #   image: mysql:latest
  #   environment:
  #     MYSQL_ROOT_PASSWORD: rootpassword
  #     MYSQL_DATABASE: gym_management
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: userpassword
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - mysql_data:/var/lib/mysql

  # MongoDB Service
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongoadminpassword
      MONGO_INITDB_DATABASE: gym_management_system
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo/:/docker-entrypoint-initdb.d/
  
      
volumes:
  # mysql_data:
  mongodb_data:
