version: '3.8'

services:

  # MongoDB Service
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongoadminpassword
      MONGO_INITDB_DATABASE: gym_management_system
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo/:/docker-entrypoint-initdb.d/
  
      
volumes:
  # mysql_data:
  mongodb_data:
